### ISSUE TITLE
Add the gcc7 label to binary package

### ISSUE THREAD

**Issue by sodre** [conda-forge/go-dep-feedstock#3]
Issue:
I would like to have go-dep available in under the gcc7 label in order to serve as a build requirement to the singularity package.

How can that label be added to repo?

cc: @isuruf

**Comment by isuruf** [comment]
If this is a binary package, shouldn't it be built with new compilers?

**Comment by sodre** [comment]
It uses the go-nocgo compiler which does not generate binaries that depend on the underlying libc. So we don't have {{ compiler('c') }} tags in them.

**Comment by isuruf** [comment]
Add

```
channel_targets:
   - conda-forge main
   - conda-forge gcc7
```

to `recipe/conda_build_config.yaml`

**Comment by sodre** [comment]
Okay, I'll give it a shot.

**Comment by sodre** [comment]
fyi, it does not look like that this worked. I am closing the issue either way since @bgruening added the label by hand.
